config/routes.rb
TP4Alonso::Application.routes.draw do 

  resources :clientepedidos

  resources :clientes

  get "user/index"

  get "user/new"

  resources :pedidos

  resources :productos

  resources :tipo_productos

  resources :users

  resources :inicio

  get "inicio/index"
  get "inicio/menu"

  match '/auth/:provider/callback' => 'sessions#create'
  match "/signout" => "sessions#destroy", :as => :signout
  match "/menu" => "inicio#menu", :as => :menu
  
  root :to => 'inicio#index'

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  attr_accessible :apellido, :cedula, :correo, :direccion, :nombre, :telefono

has_many :clienteproducto
has_many :producto, :through => :clienteproducto

#Validaciones de los distintos atributos 
validates_presence_of :apellido, :cedula, :correo, :direccion, :nombre, :telefono 

#validaciones de los aspectos que debe tener cada atributo, son tanto validaciones desde el lado del cliente como del lado del servidor
validates :cedula,
	  :presence => true,
	  :uniqueness => true,
  	  :format => {:with => /^[0-9]{9}$/ }

validates :correo,   
          :presence => true,   
          :uniqueness => true,   
          :format => { :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i }

validates :telefono,
	  :presence => true,
	  :format => {:with => /^[0-9]{8}$/ }

validates :direccion,
          :presence => true,
          :format => {:with => /^(\d|-)?(\d|,)*\.?\d*$/ }

end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clientes }
    end
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cliente }
    end
  end

  # GET /clientes/new
  # GET /clientes/new.json
  def new
    @cliente = Cliente.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cliente }
    end
  end

  # GET /clientes/1/edit
  def edit
    @cliente = Cliente.find(params[:id])
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(params[:cliente])

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'EL cliente fue registrado con exito.' }
        format.json { render json: @cliente, status: :created, location: @cliente }
      else
        format.html { render action: "new" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clientes/1
  # PUT /clientes/1.json
  def update
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      if @cliente.update_attributes(params[:cliente])
        format.html { redirect_to @cliente, notice: 'EL cliente fue actualizado con exito.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente = Cliente.find(params[:id])
    @cliente.destroy

    respond_to do |format|
      format.html { redirect_to clientes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= form_for @cliente, :validate => true do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cedula, 'Cédula' %><br />
    <%= f.number_field :cedula %>
  </div>
  <div class="field">
    <%= f.label :nombre, 'Nombre' %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellido, 'Apellido' %><br />
    <%= f.text_field :apellido %>
  </div>
  <div class="field">
    <%= f.label :telefono, 'Teléfono' %><br />
    <%= f.text_field :telefono %>
  </div>
  <div class="field">
    <%= f.label :correo, 'Email' %><br />
    <%= f.text_field :correo %>
  </div>
  <div class="field">
    <%= f.label :direccion, 'Dirección' %><br />
    <%= f.text_field :direccion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editando cliente</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @cliente %> |
<%= link_to 'Atrás', clientes_path %>

app/views/clientes/index.html.erb
<h1>Lista de clientes</h1>

<table>
  <tr>
    <th>Cedula</th>
    <th>Nombre</th>
    <th>Apellido</th>
    <th>Teléfono</th>
    <th>Correo</th>
    <th>Direccion</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clientes.each do |cliente| %>
  <tr>
    <td><%= cliente.cedula %></td>
    <td><%= cliente.nombre %></td>
    <td><%= cliente.apellido %></td>
    <td><%= cliente.telefono %></td>
    <td><%= cliente.correo %></td>
    <td><%= cliente.direccion %></td>
    <td><%= link_to 'Mostrar', cliente %></td>
    <td><%= link_to 'Editar', edit_cliente_path(cliente) %></td>
    <td><%= link_to 'Eliminar', cliente, method: :delete, data: { confirm: 'Esta seguro?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nuevo Cliente', new_cliente_path %>
<div><%= link_to 'Mi cuenta', users_path %></div>

app/views/clientes/new.html.erb
<h1>Nuevo cliente</h1>

<%= render 'form' %>

<%= link_to 'Atrás', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cedula:</b>
  <%= @cliente.cedula %>
</p>

<p>
  <b>Nombre:</b>
  <%= @cliente.nombre %>
</p>

<p>
  <b>Apellido:</b>
  <%= @cliente.apellido %>
</p>

<p>
  <b>Teléfono:</b>
  <%= @cliente.telefono %>
</p>

<p>
  <b>Correo:</b>
  <%= @cliente.correo %>
</p>

<p>
  <b>Direccion:</b>
  <%= @cliente.direccion %>
</p>


<%= link_to 'Editar', edit_cliente_path(@cliente) %> |
<%= link_to 'Atrás', clientes_path %>