config/routes.rb
TP4Alonso::Application.routes.draw do 

  resources :clientepedidos

  resources :clientes

  get "user/index"

  get "user/new"

  resources :pedidos

  resources :productos

  resources :tipo_productos

  resources :users

  resources :inicio

  get "inicio/index"
  get "inicio/menu"

  match '/auth/:provider/callback' => 'sessions#create'
  match "/signout" => "sessions#destroy", :as => :signout
  match "/menu" => "inicio#menu", :as => :menu
  
  root :to => 'inicio#index'

end

app/models/clientepedido.rb
class Clientepedido < ActiveRecord::Base
  attr_accessible :cantidad, :cliente_id, :producto_id

#RElaciones de la tabla intermedia
belongs_to :cliente
belongs_to :producto

#Validaciones de los distintos atributos 
validates_presence_of :cantidad, :cliente_id, :producto_id

#Validaciones, tanto del lado del cliente como del lado del servidor
validates :cantidad,
	  :presence => true,
  	  :format => {:with => /^[0-9]{1,}$/ }

end

app/controllers/clientepedidos_controller.rb
class ClientepedidosController < ApplicationController
  # GET /clientepedidos
  # GET /clientepedidos.json
  def index
    @clientepedidos = Clientepedido.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clientepedidos }
    end
  end

  # GET /clientepedidos/1
  # GET /clientepedidos/1.json
  def show
    @clientepedido = Clientepedido.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @clientepedido }
    end
  end

  # GET /clientepedidos/new
  # GET /clientepedidos/new.json
  def new
    @clientepedido = Clientepedido.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @clientepedido }
    end
  end

  # GET /clientepedidos/1/edit
  def edit
    @clientepedido = Clientepedido.find(params[:id])
  end

  # POST /clientepedidos
  # POST /clientepedidos.json
  def create
    @clientepedido = Clientepedido.new(params[:clientepedido])       #Obtiene los datos del clientepedido
    @cantidadCliente = @clientepedido.cantidad		    #cantidad de producto solicitado por el cliente
    @cantidadProducto = Producto.find(@clientepedido.producto_id).cantidad   #cantidad de ese producto
    @cantidadActual = @cantidadProducto - @cantidadCliente	#Cantidad actualizada
    @idProducto = Producto.find(@clientepedido.producto_id).id  #Permite obtener el id del producto
#      raise @idProducto.to_yaml

   if @cantidadCliente > @cantidadProducto
    	flash[:notice] = "No hay suficiente cantidades en el inventario"
        render :new
   else
    respond_to do |format|
      if @clientepedido.save
	format.html { redirect_to @clientepedido, notice: 'EL pedido fue registrado con exito.' }
	format.json { render json: @clientepedido, status: :created, location: @clientepedido }
Producto.find(@idProducto).update_attribute(:cantidad, @cantidadActual) #Actualiza la cantidad de ese producto del inventario
      else
	format.html { render action: "new" }
	format.json { render json: @clientepedido.errors, status: :unprocessable_entity }
      end
     end
    end
   end

  # PUT /clientepedidos/1
  # PUT /clientepedidos/1.json
  def update
    @clientepedido = Clientepedido.find(params[:id])

    respond_to do |format|
      if @clientepedido.update_attributes(params[:clientepedido])
        format.html { redirect_to @clientepedido, notice: 'EL pedido fue actualizado.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @clientepedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientepedidos/1
  # DELETE /clientepedidos/1.json
  def destroy
    @clientepedido = Clientepedido.find(params[:id])
    @clientepedido.destroy

    respond_to do |format|
      format.html { redirect_to clientepedidos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/clientepedidos_helper.rb
module ClientepedidosHelper
end

app/views/clientepedidos/_form.html.erb
<%= form_for @clientepedido, :validate => true do |f| %>
  <% if @clientepedido.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clientepedido.errors.count, "error") %> prohibited this clientepedido from being saved:</h2>

      <ul>
      <% @clientepedido.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<p id="notice"><%= notice%></p>

  <div class="field">
    <%= f.label :cliente_id, 'Cliente:' %><br />
    <%= f.collection_select :cliente_id, Cliente.all, :id, :nombre%><br />
  </div>
  <div class="field">
    <%= f.label :producto_id, 'Producto:' %><br />
    <%= f.collection_select :producto_id, Producto.all, :id, :nombre %><br />
  </div>
  <div class="field">
    <%= f.label :cantidad %><br />
    <%= f.number_field :cantidad %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clientepedidos/edit.html.erb
<h1>Editing clientepedido</h1>

<%= render 'form' %>

<%= link_to 'Show', @clientepedido %> |
<%= link_to 'Back', clientepedidos_path %>

app/views/clientepedidos/index.html.erb
<h1>Listado de pedidos</h1>

<table>
  <tr>
    <th>Cliente</th>
    <th>Apellido</th>
    <th>Producto</th>
    <th>Cantidad</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clientepedidos.each do |clientepedido| %>
  <tr>
    <td><%= Cliente.find(clientepedido.cliente_id).nombre %></td>
    <td><%= Cliente.find(clientepedido.cliente_id).apellido %></td>
    <td><%= Producto.find(clientepedido.producto_id).nombre %></td>
    <td><%= clientepedido.cantidad %></td>
    <td><%= link_to 'Mostrar', clientepedido %></td>
    <td><%= link_to 'Editar', edit_clientepedido_path(clientepedido) %></td>
    <td><%= link_to 'Eliminar', clientepedido, method: :delete, data: { confirm: 'Está seguro?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nuevo pedido', new_clientepedido_path %>
<%= link_to 'Mi cuenta', users_path%>

app/views/clientepedidos/new.html.erb
<h1>Nuevo pedido</h1>

<%= render 'form' %>

<%= link_to 'Atrás', clientepedidos_path %>

app/views/clientepedidos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cliente:</b>
  <%= Cliente.find(@clientepedido.cliente_id).nombre %>
  <%= Cliente.find(@clientepedido.cliente_id).apellido %>
</p>

<p>
  <b>Producto:</b>
  <%= Producto.find(@clientepedido.producto_id).nombre %>
</p>

<p>
  <b>Cantidad:</b>
  <%= @clientepedido.cantidad %>
</p>


<%= link_to 'Editar', edit_clientepedido_path(@clientepedido) %> |
<%= link_to 'Atrás', clientepedidos_path %>