config/routes.rb
TP4Alonso::Application.routes.draw do 

  resources :clientepedidos

  resources :clientes

  get "user/index"

  get "user/new"

  resources :pedidos

  resources :productos

  resources :tipo_productos

  resources :users

  resources :inicio

  get "inicio/index"
  get "inicio/menu"

  match '/auth/:provider/callback' => 'sessions#create'
  match "/signout" => "sessions#destroy", :as => :signout
  match "/menu" => "inicio#menu", :as => :menu
  
  root :to => 'inicio#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :apellido, :cedula, :correo, :direccion, :nombre, :provider, :uid

has_many :pedido
has_many :producto, :through => :pedido

#Validaciones de los distintos atributos 
#validates_presence_of :apellido, :cedula, :correo, :direccion, :nombre  
#validates :correo,   
#          :presence => true,   
#          :uniqueness => true,   
#          :format => { :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i }

#método que permite hacer la autenticación con twitter
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.cedula = auth["info"]["cedula"]
      user.nombre = auth["info"]["nombre"]
      user.apellido = auth["info"]["apellido"]
      user.correo = auth["info"]["correo"]
      user.direccion = auth["info"]["direccion"]
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Usuario creado correctamente.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'Usuario actualizado correctamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> El cliente no se ha registrado:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %> 

  <div class="field">
    <%f.label :provider %>
    <% @user.provider %>
  </div>
  <div class="field">
    <%f.label :uid %>
    <% @user.uid %>
  </div>
 <div class="field">
    <%= f.label :cedula, 'Cedula' %><br />
    <%= f.number_field :cedula %>
  </div>
  <div class="field">
    <%= f.label :nombre, 'Nombre' %><br />
    <%= f.text_field :nombre%>
  </div>
  <div class="field">
    <%= f.label :apellido, 'Apellido' %><br />
    <%= f.text_field :apellido%>
  </div>
  <div class="field">
    <%= f.label :correo, 'Email' %><br />
    <%= f.text_field :correo%>
  </div>
  <div class="field">
    <%= f.label :direccion, 'Dirección' %><br />
    <%= f.text_field :direccion%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editando  mi cuenta</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @user %> |
<%= link_to 'Atrás', users_path %>

app/views/users/index.html.erb
<h1>Mi cuenta</h1>

<table>
  <tr>
    <th>Cedula</th>
    <th>Nombre</th>
    <th>Apellido</th>
    <th>Correo</th>
    <th>Direccion</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.cedula %></td>
    <td><%= user.nombre %></td>
    <td><%= user.apellido %></td>
    <td><%= user.correo %></td>
    <td><%= user.direccion %></td>
    <td><%= link_to 'Mostrar', user %></td>
    <td><%= link_to 'Editar', edit_user_path(user) %></td>
    <td><%= link_to 'Eliminar', user, method: :delete, data: { confirm: 'Esta seguro?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Registrar o Actualizar mi información', edit_user_path(current_user) %>
<div>
<%= link_to 'Ver clientes', clientes_path%>
<%= link_to 'Gestionar catálogo', productos_path%>
<%= link_to 'Realizar pedido', clientepedidos_path%>
</div>

app/views/users/new.html.erb
<h1>New producto</h1>

<%= render 'form' %>

<%= link_to 'Back', productos_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cédula:</b>
  <%= @user.cedula %>
</p>

<p>
  <b>Nombre:</b>
  <%= @user.nombre %>
</p>

<p>
  <b>Apellido:</b>
  <%= @user.apellido %>
</p>

<p>
  <b>Correo:</b>
  <%= @user.correo %>
</p>

<p>
  <b>Direccion:</b>
  <%= @user.direccion %>
</p>

<%= link_to 'Editar', edit_user_path(@user) %> |
<%= link_to 'Atrás', users_path %>