config/routes.rb
TP4Alonso::Application.routes.draw do 

  resources :clientepedidos

  resources :clientes

  get "user/index"

  get "user/new"

  resources :pedidos

  resources :productos

  resources :tipo_productos

  resources :users

  resources :inicio

  get "inicio/index"
  get "inicio/menu"

  match '/auth/:provider/callback' => 'sessions#create'
  match "/signout" => "sessions#destroy", :as => :signout
  match "/menu" => "inicio#menu", :as => :menu
  
  root :to => 'inicio#index'

end

app/models/producto.rb
#Clase producto, tiene todos los datos de los productos
class Producto < ActiveRecord::Base
  attr_accessible :cantidad, :descripcion, :image, :marca, :nombre, :precio, :tipoProducto_id, :remote_image_url

#Relaciones para el manejo de la base de datos
belongs_to :tipo_producto

has_many :pedido
has_many :user, :through => :pedido

#permite la relacion entre la tabla de clientes y productos
has_many :clienteproducto
has_many :cliente, :through => :clienteproducto

  mount_uploader :image, ImageUploader        #Permite la gestión de imágenes 

#Validaciones de los distintos atributos 
validates_presence_of :cantidad, :descripcion, :marca, :nombre, :precio, :tipoProducto_id

validates :precio,
	  :presence => true,
	  :format => {:with => /^[0-9]{8}$/ }

validates :cantidad,
          :presence => true,
          :format => {:with => /^[0-9]{9}$/ }

#Método que permite validar la cantidad en inventario
#def validarInventario
#  if cantidad.present? 
    

end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @productos }
    end
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
    @producto = Producto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @producto }
    end
  end

  # GET /productos/new
  # GET /productos/new.json
  def new
    @producto = Producto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @producto }
    end
  end

  # GET /productos/1/edit
  def edit
    @producto = Producto.find(params[:id])
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(params[:producto])

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render json: @producto, status: :created, location: @producto }
      else
        format.html { render action: "new" }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /productos/1
  # PUT /productos/1.json
  def update
    @producto = Producto.find(params[:id])

    respond_to do |format|
      if @producto.update_attributes(params[:producto])
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto = Producto.find(params[:id])
    @producto.destroy

    respond_to do |format|
      format.html { redirect_to productos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/productos/_form.html.erb
<%= form_for @producto, :validate => true, :html => {:multipart => true} do |f| %>
  <% if @producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% @producto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipoProducto_id, 'Tipo de producto' %><br />
    <%= f.collection_select :tipoProducto_id, TipoProducto.all, :id, :nombre %><br />
  </div>
  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :marca %><br />
    <%= f.text_field :marca %>
  </div>
  <div class="field">
    <%= f.label :precio %><br />
    <%= f.text_field :precio %>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :cantidad %><br />
    <%= f.number_field :cantidad %>
  </div>
  </div>
    <%= f.label :image, 'Imagen' %><br />
    <%= f.file_field :image %><br />
  </div>
    <%= f.label :remote_image_url, 'o imagen desde url' %><br />
    <%= f.text_field :remote_image_url %><br />
  </div> 
 </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/productos/edit.html.erb
<h1>Editando producto</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @producto %> |
<%= link_to 'Atrás', productos_path %>

app/views/productos/index.html.erb
<h1>Lista de productos</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Marca</th>
    <th>Precio</th>
    <th>Imagen</th>
    <th>Descripcion</th>
    <th>Cantidad</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @productos.each do |producto| %>
 <tr>
    <td><%= producto.nombre %></td>
    <td><%= producto.marca %></td>
    <td>¢<%= producto.precio %></td>
    <td><%= image_tag producto.image_url(:thumb).to_s %></td>
    <td><%= producto.descripcion %></td>
    <td><%= producto.cantidad %></td>
    <td><%= link_to 'Motrar', producto %></td>
    <td><%= link_to 'Editar', edit_producto_path(producto) %></td>
    <td><%= link_to 'Eliminar', producto, method: :delete, data: { confirm: 'Está seguro?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nuevo producto', new_producto_path %>
<%= link_to 'Nuevo tipo de producto', tipo_productos_path %>
<%= link_to 'Volver a mi cuenta', users_path %>

app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Tipo producto:</b>
  <%= TipoProducto.find(@producto.tipoProducto_id).nombre %>
</p>

<p>
  <b>Nombre:</b>
  <%= @producto.nombre %>
</p>

<p>
  <b>Marca:</b>
  <%= @producto.marca %>
</p>

<p>
  <b>Precio:</b>
  ¢<%= @producto.precio %>
</p>

<p>
  <b>Imagen:</b>
  <%= image_tag @producto.image_url(:thumb).to_s %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @producto.descripcion %>
</p>

<p>
  <b>Cantidad:</b>
  <%= @producto.cantidad %>
</p>


<%= link_to 'Editar', edit_producto_path(@producto) %> |
<%= link_to 'Atrás', productos_path %>